apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-tdx-qgs
spec:
  selector:
    matchLabels:
      app: intel-tdx-qgs
  template:
    metadata:
      labels:
        app: intel-tdx-qgs
    spec:
      serviceAccountName: intel-tdx-dcap-qgs
      priorityClassName: system-node-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      - name: platform-registration
        image: intel-tdx-qgs:latest
        imagePullPolicy: IfNotPresent
        command:
        - pck-cert-tool
        - get-platforms
        - -p
        - /usr/local/bin/get_platform_info
        - -n
        - $(NAMESPACE)
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
        volumeMounts:
        - name: efivars
          mountPath: /sys/firmware/efi/efivars
      - name: pck-certs-watcher
        image: intel-tdx-qgs:latest
        imagePullPolicy: IfNotPresent
        restartPolicy: Always
        command:
        - pck-cert-tool
        - get-certificates
        - -p
        - /usr/local/bin/get_platform_info
        - -n
        - $(NAMESPACE)
        - -o
        - /run/dcap/cache/.dcap-qcnl
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "100m"
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
        volumeMounts:
        - name: dcap-qcnl-cache
          mountPath: /run/dcap/cache/
        startupProbe:
          exec:
            command:
            - pck-cert-tool
            - probe
            - cache-ready
            - /run/dcap/cache/.dcap-qcnl
          periodSeconds: 10
          failureThreshold: 2147483647
      containers:
      - name: tdx-qgs
        image: intel-tdx-qgs:latest
        args:
        - -n=4
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsUser: 0
          runAsGroup: 992
          seLinuxOptions:
            type: spc_t
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "200m"
            sgx.intel.com/enclave: 1
            sgx.intel.com/provision: 1
        imagePullPolicy: IfNotPresent
        env:
        - name: XDG_CACHE_HOME
          value: "/run/dcap/cache"
        startupProbe:
          exec:
            command:
            - pck-cert-tool
            - probe
            - check-socket
            - /var/run/tdx-qgs/qgs.socket
          periodSeconds: 2
          failureThreshold: 30
        livenessProbe:
          exec:
            command:
            - pck-cert-tool
            - probe
            - check-socket
            - /var/run/tdx-qgs/qgs.socket
          periodSeconds: 60
        volumeMounts:
        - name: dcap-qcnl-cache
          mountPath: /run/dcap/cache
          readOnly: true
        - name: qgs-socket
          mountPath: /var/run/tdx-qgs
      volumes:
      - name: dcap-qcnl-cache
        emptyDir:
          medium: Memory
          sizeLimit: 1Mi
      - name: qgs-socket
        hostPath:
          path: /var/run/tdx-qgs
          type: DirectoryOrCreate
      - name: efivars
        hostPath:
          path: /sys/firmware/efi/efivars/
